Predict the Emotion state using an EGG signals

### Features:
PCA\\
ICA\\

### Classifier:
Random Forest \\
XGBoost \\
AdaBoostClassifier \\

## Import Libraries

In [2]:
import numpy as np
import pandas as pd

#import matplotlib.pyplot as plt
#import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

#import time
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier


## Upload the Data

In [3]:
from google.colab import files
uploaded = files.upload()

Saving emotions.csv to emotions.csv


# Read the data

In [5]:
import io
df = pd.read_csv(io.StringIO(uploaded['emotions.csv'].decode('utf-8')))
df.head()

# mean_0_a  mean_1_a  mean_2_a  ...  fft_748_b  fft_749_b     label
0        4.62      30.3    -356.0  ...    -162.00     280.00  NEGATIVE
1       28.80      33.1      32.0  ...     -31.60       2.57   NEUTRAL
2        8.90      29.4    -416.0  ...    -148.00     281.00  POSITIVE
3       14.90      31.6    -143.0  ...       9.53     -12.40  POSITIVE
4       28.30      31.3      45.2  ...      23.90     -17.60   NEUTRAL

[5 rows x 2549 columns]

# Preprocessing

In [6]:
df['label'] = df['label'].map({'NEGATIVE': -1, 'POSITIVE': 1,'NEUTRAL': 0 })

In [7]:
df.head()

# mean_0_a  mean_1_a  mean_2_a  ...  fft_748_b  fft_749_b  label
0        4.62      30.3    -356.0  ...    -162.00     280.00     -1
1       28.80      33.1      32.0  ...     -31.60       2.57      0
2        8.90      29.4    -416.0  ...    -148.00     281.00      1
3       14.90      31.6    -143.0  ...       9.53     -12.40      1
4       28.30      31.3      45.2  ...      23.90     -17.60      0

[5 rows x 2549 columns]

In [8]:
df.shape

(2132, 2549)

# Independent and Depemdent variables

In [10]:
X = df.drop(['label'], axis = 1)
y = df['label']

# Define the Classifiers, PCA

In [11]:
from sklearn import decomposition

pcaRandom =decomposition.PCA(n_components=36)# with RandomForest
X_pcaRandom = pcaRandom.fit_transform(X)

pcaXGBoost =decomposition.PCA(n_components=33)# with XGBoost
X_pcaXGBoost = pcaXGBoost.fit_transform(X)

pcaAdaboost =decomposition.PCA(n_components=28)# with AdaBoost
X_pcaAdaboost = pcaAdaboost.fit_transform(X)

In [32]:
def PCA_Random():
 
   
  modelRandom= RandomForestClassifier(bootstrap=False,  max_depth= 100, max_features='auto',min_samples_leaf=1,
                          min_samples_split= 2, n_estimators=400)#Random

  scorePCArandom = cross_val_score(modelRandom, X_pcaRandom, y , cv=cv, n_jobs=-1)

  print('Accuracy of PCA Random: %.3f (%.3f)' % (mean(scorePCArandom), std(scorePCArandom)))


  #print(cross_val_score(modelRandom,X_pcaRandom, y, cv=cv, n_jobs=-1))



In [24]:
def PCA_XGboost():
    
#cv = KFold(n_splits=10, random_state=1, shuffle=True)


  modelXGBoost= XGBClassifier(bootstrap=True,  max_depth= 20, max_features='auto',min_samples_leaf=1,
                         min_samples_split= 2, n_estimators=2000)#XGBoost

  scorePCAxgboost = cross_val_score(modelXGBoost, X_pcaXGBoost, y , cv=cv, n_jobs=-1)

  print('Accuracy of PCA XGboost: %.3f (%.3f)' % (mean(scorePCAxgboost), std(scorePCAxgboost)))


In [27]:
def PCA_Adaboost():

  modelAdaBoost= AdaBoostClassifier(algorithm='SAMME', learning_rate= 0.01, n_estimators=2000)


  scorePCAadaboost = cross_val_score(modelAdaBoost, X_pcaAdaboost, y , cv=cv, n_jobs=-1)

  print('Accuracy of PCA AdaBoost: %.3f (%.3f)' % (mean(scorePCAadaboost), std(scorePCAadaboost)))




In [33]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
   
cv = KFold(n_splits=10, random_state=1, shuffle=True)

PCA_Random()

PCA_XGboost()

PCA_Adaboost()

Accuracy of PCA Random: 0.946 (0.014)
[0.96261682 0.94392523 0.95305164 0.97183099 0.9342723  0.92488263
 0.92957746 0.94835681 0.95305164 0.95774648]
Accuracy of PCA XGboost: 0.946 (0.016)
Accuracy of PCA AdaBoost: 0.856 (0.026)


# Define the Classifiers, ICA

In [53]:
from sklearn.decomposition import FastICA
from sklearn import decomposition

IcaRandom =FastICA(n_components=33)# with RandomForest
X_icaRandom = IcaRandom.fit_transform(X)

IcaXGBoost =FastICA(n_components=31)# with XGBoost
X_icaXGBoost = IcaXGBoost.fit_transform(X)

IcaAdaboost =FastICA(n_components=31)# with AdaBoost
X_icaAdaboost = IcaAdaboost.fit_transform(X)


KeyboardInterrupt: ignored

In [ ]:
def ICA_Random():
 
   
  modelRandomICA= RandomForestClassifier(bootstrap=True,  max_depth= 60, max_features='sqrt',min_samples_leaf=1,
                          min_samples_split= 5, n_estimators=400)#Random

  scoreICArandom = cross_val_score(modelRandomICA, X_icaRandom, y , cv=cv, n_jobs=-1)

  print('Accuracy of ICA Random: %.3f (%.3f)' % (mean(scoreICArandom), std(scoreICArandom)))




In [ ]:
def ICA_XGboost():
    

  modelXGBoostICA= XGBClassifier(bootstrap=True,  max_depth= 20, max_features='auto',min_samples_leaf=1,
                         min_samples_split= 2, n_estimators=800)#XGBoost

  scoreICAxgboost = cross_val_score(modelXGBoostICA, X_icaXGBoost, y , cv=cv, n_jobs=-1)

  print('Accuracy of PCA XGboost: %.3f (%.3f)' % (mean(scoreICAxgboost), std(scoreICAxgboost)))

In [ ]:
def ICA_Adaboost():

  modelAdaBoostICA= AdaBoostClassifier(algorithm='SAMME', learning_rate= 0.3, n_estimators=1600)


  scoreICAadaboost = cross_val_score(modelAdaBoostICA, X_icaAdaboost, y , cv=cv, n_jobs=-1)

  print('Accuracy of PCA AdaBoost: %.3f (%.3f)' % (mean(scoreICAadaboost), std(scoreICAadaboost)))


In [ ]:

ICA_Random()

ICA_XGboost()

ICA_Adaboost()

 **Below code, i use it to record the values in table 5, this example for the pca&adaboost**



In [54]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
pcaX_Train, pcaX_Test, pcaY_Train, pcaY_Test = train_test_split(X_pcaAdaboost, y, 
                                                        test_size = 0.20, 
                                                        random_state = 100)

In [55]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

modelrandomP = AdaBoostClassifier (algorithm='SAMME', learning_rate= 0.01, n_estimators=2000).fit(pcaX_Train,pcaY_Train)


predictionAda = modelrandomP.predict(pcaX_Test)

print(confusion_matrix(pcaY_Test,predictionAda))
print(classification_report(pcaY_Test,predictionAda))


[[149   1   4]
 [  2 135  11]
 [ 33   9  83]]
              precision    recall  f1-score   support

          -1       0.81      0.97      0.88       154
           0       0.93      0.91      0.92       148
           1       0.85      0.66      0.74       125

    accuracy                           0.86       427
   macro avg       0.86      0.85      0.85       427
weighted avg       0.86      0.86      0.86       427

